Export env vars directly. Propagate exit codes.

diff --git a/scripts/cibuild b/scripts/cibuild
--- a/scripts/cibuild
+++ b/scripts/cibuild
@@ -7,10 +7,10 @@
 
 echo "===> Starting scripts/cibuild"
 
-DATABASE_URL=ignored
-SECRET_KEY=supersecretkey
-SENTRY_DSN=ignored
-EXPORT_PREFIX=ignored
+export DATABASE_URL=ignored
+export SECRET_KEY=supersecretkey
+export SENTRY_DSN=ignored
+export EXPORT_PREFIX=ignored
 # Found this one-liner via http://stackoverflow.com/a/246128. Thanks!
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 # The script dir is checkniner/scripts. The site root will be up one level.
@@ -22,20 +22,12 @@ echo "     SENTRY_DSN:    ignored"
 echo "     EXPORT_PREFIX: ignored"
 echo "     SITE_ROOT:     $SITE_ROOT"
 
-
-echo "===> Setting CI env vars"
-echo "export DATABASE_URL=$DATABASE_URL" >> $SITE_ROOT/bin/activate
-echo "export SECRET_KEY=$SECRET_KEY" >> $SITE_ROOT/bin/activate
-echo "export SENTRY_DSN=$SENTRY_DSN" >> $SITE_ROOT/bin/activate
-echo "export EXPORT_PREFIX=$EXPORT_PREFIX" >> $SITE_ROOT/bin/activate
-
-
 echo "===> Installing pip packages for testing"
-source $SITE_ROOT/bin/activate
 pip install -r $SITE_ROOT/requirements/development.txt
-
 
 echo "===> Passing the baton to scripts/test"
 $SITE_ROOT/scripts/test
 
-echo "===> cibuild completed"
+# Upon exiting, return the exit code from scripts/test. This will tell the CI
+# system whether or not the tests passed.
+exit $?
